load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//xlab:internal"])

rust_library(
    name = "security_id",
    srcs = [
        "src/lib.rs",
    ],
    crate_name = "security_id_lib",
    edition = "2021",
)
