load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//xlab:internal"])


py_library(
    name = "notebook_deps",
    srcs_version = "PY3",
    deps = [
        "//xlab/util/itertools:groupby",
    ],
)
