load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//xlab:internal"])

rust_library(
    name = "order",
    srcs = [
        "src/lib.rs",
        "src/order.rs",
    ],
    edition = "2021",
)

